### ISSUE TITLE
be able to add label "linear" to github ticket to sync into linear

### ISSUE THREAD

**Issue by PeerRich** [calcom/linear-to-github#13]
if a community member creates a ticket in github, it would be great to give it a "linear" label to sync it into linear

**Comment by tedspare** [comment]
Added in 1505a20

Can test by adding the "linear" label to an issue opened by a non-member

**Comment by tedspare** [comment]
Added instructions to landing page in 6b4760e70ad4201444d61b5b51a6fca38155c76e
